#docker compose -p marketplace-dev -f compose-dev.yaml up -d
#docker compose -p marketplace-dev -f compose-dev.yaml down -v
#go run -tags postgres github.com/golang-migrate/migrate/v4/cmd/migrate@latest -verbose -path ./migrations/catalog -database "postgres://postgres:123456789@localhost:9101/catalog_db_dev?sslmode=disable" up

services:
  catalog_db_dev:
    container_name: catalog_db_dev
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: catalog_db_dev
    ports:
      - "9101:5432"
    volumes:
      - postrgres_catalog_dev:/var/lib/postgresql/data
    networks:
      - marketplace_dev_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postrgres_catalog_dev:

networks:
  marketplace_dev_net:
    driver: bridge