#docker compose -p shop-dev -f compose-dev.yaml up -d
#docker compose -p shop-dev -f compose-dev.yaml down -v
#go run -tags postgres github.com/golang-migrate/migrate/v4/cmd/migrate@latest -verbose -path ./migrations/catalog -database "postgres://postgres:123456789@localhost:9101/catalog-db-dev?sslmode=disable" up

services:
  catalog-db-dev:
    container_name: catalog-db-dev
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: catalog-db-dev
    ports:
      - "9101:5432"
    volumes:
      - postgres-catalog-dev:/var/lib/postgresql/data
    networks:
      - shop-dev-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  basket-db-dev:
    container_name: basket-db-dev
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: basket-db-dev
    ports:
      - "9102:5432"
    volumes:
      - postgres-basket-dev:/var/lib/postgresql/data
    networks:
      - shop-dev-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  basket-cache-redis-dev:
    container_name: basket-redis-dev
    image: redis:7
    command: redis-server --requirepass "123456789" --protected-mode no
    restart: always
    ports:
      - "9112:6379"
    volumes:
      - redis-basket-dev:/data 
    networks:
      - shop-dev-net

  promotion-db:
    container_name: promotion-db-dev
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=promotion-db
    restart: always
    ports:
      - "9103:3306"
    volumes:
      - mysql-promotion:/var/lib/mysql
    networks:
      - shop-dev-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456789"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  postgres-catalog-dev:
  postgres-basket-dev:
  redis-basket-dev:
  mysql-promotion:

networks:
  shop-dev-net:
    driver: bridge
