// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: promo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPromoByCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogItemId string                 `protobuf:"bytes,1,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoByCatalogItemRequest) Reset() {
	*x = GetPromoByCatalogItemRequest{}
	mi := &file_promo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoByCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoByCatalogItemRequest) ProtoMessage() {}

func (x *GetPromoByCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoByCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*GetPromoByCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{0}
}

func (x *GetPromoByCatalogItemRequest) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

type GetPromoByCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promotion     *Promotion             `protobuf:"bytes,1,opt,name=promotion,proto3" json:"promotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoByCatalogItemResponse) Reset() {
	*x = GetPromoByCatalogItemResponse{}
	mi := &file_promo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoByCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoByCatalogItemResponse) ProtoMessage() {}

func (x *GetPromoByCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoByCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*GetPromoByCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{1}
}

func (x *GetPromoByCatalogItemResponse) GetPromotion() *Promotion {
	if x != nil {
		return x.Promotion
	}
	return nil
}

type Promotion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CatalogItemId string                 `protobuf:"bytes,2,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promotion) Reset() {
	*x = Promotion{}
	mi := &file_promo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promotion) ProtoMessage() {}

func (x *Promotion) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promotion.ProtoReflect.Descriptor instead.
func (*Promotion) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{2}
}

func (x *Promotion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Promotion) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

func (x *Promotion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Promotion) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CreatePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogItemId string                 `protobuf:"bytes,1,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromoRequest) Reset() {
	*x = CreatePromoRequest{}
	mi := &file_promo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromoRequest) ProtoMessage() {}

func (x *CreatePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromoRequest.ProtoReflect.Descriptor instead.
func (*CreatePromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePromoRequest) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

func (x *CreatePromoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePromoRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CreatePromoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromoResponse) Reset() {
	*x = CreatePromoResponse{}
	mi := &file_promo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromoResponse) ProtoMessage() {}

func (x *CreatePromoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromoResponse.ProtoReflect.Descriptor instead.
func (*CreatePromoResponse) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePromoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePromoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePromoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdatePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePromoRequest) Reset() {
	*x = UpdatePromoRequest{}
	mi := &file_promo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromoRequest) ProtoMessage() {}

func (x *UpdatePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromoRequest.ProtoReflect.Descriptor instead.
func (*UpdatePromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePromoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePromoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePromoRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdatePromoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePromoResponse) Reset() {
	*x = UpdatePromoResponse{}
	mi := &file_promo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePromoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromoResponse) ProtoMessage() {}

func (x *UpdatePromoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromoResponse.ProtoReflect.Descriptor instead.
func (*UpdatePromoResponse) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePromoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePromoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeletePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromoRequest) Reset() {
	*x = DeletePromoRequest{}
	mi := &file_promo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromoRequest) ProtoMessage() {}

func (x *DeletePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromoRequest.ProtoReflect.Descriptor instead.
func (*DeletePromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePromoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePromoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromoResponse) Reset() {
	*x = DeletePromoResponse{}
	mi := &file_promo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromoResponse) ProtoMessage() {}

func (x *DeletePromoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromoResponse.ProtoReflect.Descriptor instead.
func (*DeletePromoResponse) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePromoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePromoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_promo_proto protoreflect.FileDescriptor

const file_promo_proto_rawDesc = "" +
	"\n" +
	"\vpromo.proto\x12\tpromotion\"F\n" +
	"\x1cGetPromoByCatalogItemRequest\x12&\n" +
	"\x0fcatalog_item_id\x18\x01 \x01(\tR\rcatalogItemId\"S\n" +
	"\x1dGetPromoByCatalogItemResponse\x122\n" +
	"\tpromotion\x18\x01 \x01(\v2\x14.promotion.PromotionR\tpromotion\"o\n" +
	"\tPromotion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fcatalog_item_id\x18\x02 \x01(\tR\rcatalogItemId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"h\n" +
	"\x12CreatePromoRequest\x12&\n" +
	"\x0fcatalog_item_id\x18\x01 \x01(\tR\rcatalogItemId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"a\n" +
	"\x13CreatePromoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"P\n" +
	"\x12UpdatePromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"Q\n" +
	"\x13UpdatePromoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"$\n" +
	"\x12DeletePromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x13DeletePromoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2\xe8\x02\n" +
	"\x10PromotionService\x12j\n" +
	"\x15GetPromoByCatalogItem\x12'.promotion.GetPromoByCatalogItemRequest\x1a(.promotion.GetPromoByCatalogItemResponse\x12L\n" +
	"\vCreatePromo\x12\x1d.promotion.CreatePromoRequest\x1a\x1e.promotion.CreatePromoResponse\x12L\n" +
	"\vUpdatePromo\x12\x1d.promotion.UpdatePromoRequest\x1a\x1e.promotion.UpdatePromoResponse\x12L\n" +
	"\vDeletePromo\x12\x1d.promotion.DeletePromoRequest\x1a\x1e.promotion.DeletePromoResponseB:Z8github.com/n0en0o/marketplace/internal/promotion/grpc/pbb\x06proto3"

var (
	file_promo_proto_rawDescOnce sync.Once
	file_promo_proto_rawDescData []byte
)

func file_promo_proto_rawDescGZIP() []byte {
	file_promo_proto_rawDescOnce.Do(func() {
		file_promo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_promo_proto_rawDesc), len(file_promo_proto_rawDesc)))
	})
	return file_promo_proto_rawDescData
}

var file_promo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_promo_proto_goTypes = []any{
	(*GetPromoByCatalogItemRequest)(nil),  // 0: promotion.GetPromoByCatalogItemRequest
	(*GetPromoByCatalogItemResponse)(nil), // 1: promotion.GetPromoByCatalogItemResponse
	(*Promotion)(nil),                     // 2: promotion.Promotion
	(*CreatePromoRequest)(nil),            // 3: promotion.CreatePromoRequest
	(*CreatePromoResponse)(nil),           // 4: promotion.CreatePromoResponse
	(*UpdatePromoRequest)(nil),            // 5: promotion.UpdatePromoRequest
	(*UpdatePromoResponse)(nil),           // 6: promotion.UpdatePromoResponse
	(*DeletePromoRequest)(nil),            // 7: promotion.DeletePromoRequest
	(*DeletePromoResponse)(nil),           // 8: promotion.DeletePromoResponse
}
var file_promo_proto_depIdxs = []int32{
	2, // 0: promotion.GetPromoByCatalogItemResponse.promotion:type_name -> promotion.Promotion
	0, // 1: promotion.PromotionService.GetPromoByCatalogItem:input_type -> promotion.GetPromoByCatalogItemRequest
	3, // 2: promotion.PromotionService.CreatePromo:input_type -> promotion.CreatePromoRequest
	5, // 3: promotion.PromotionService.UpdatePromo:input_type -> promotion.UpdatePromoRequest
	7, // 4: promotion.PromotionService.DeletePromo:input_type -> promotion.DeletePromoRequest
	1, // 5: promotion.PromotionService.GetPromoByCatalogItem:output_type -> promotion.GetPromoByCatalogItemResponse
	4, // 6: promotion.PromotionService.CreatePromo:output_type -> promotion.CreatePromoResponse
	6, // 7: promotion.PromotionService.UpdatePromo:output_type -> promotion.UpdatePromoResponse
	8, // 8: promotion.PromotionService.DeletePromo:output_type -> promotion.DeletePromoResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_promo_proto_init() }
func file_promo_proto_init() {
	if File_promo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_promo_proto_rawDesc), len(file_promo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_promo_proto_goTypes,
		DependencyIndexes: file_promo_proto_depIdxs,
		MessageInfos:      file_promo_proto_msgTypes,
	}.Build()
	File_promo_proto = out.File
	file_promo_proto_goTypes = nil
	file_promo_proto_depIdxs = nil
}
