// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: promo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPromoByCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogItemId string                 `protobuf:"bytes,1,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoByCatalogItemRequest) Reset() {
	*x = GetPromoByCatalogItemRequest{}
	mi := &file_promo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoByCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoByCatalogItemRequest) ProtoMessage() {}

func (x *GetPromoByCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoByCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*GetPromoByCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{0}
}

func (x *GetPromoByCatalogItemRequest) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

type GetPromoByCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promotion     *Promotion             `protobuf:"bytes,1,opt,name=promotion,proto3" json:"promotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoByCatalogItemResponse) Reset() {
	*x = GetPromoByCatalogItemResponse{}
	mi := &file_promo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoByCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoByCatalogItemResponse) ProtoMessage() {}

func (x *GetPromoByCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoByCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*GetPromoByCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{1}
}

func (x *GetPromoByCatalogItemResponse) GetPromotion() *Promotion {
	if x != nil {
		return x.Promotion
	}
	return nil
}

type Promotion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CatalogItemId string                 `protobuf:"bytes,2,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promotion) Reset() {
	*x = Promotion{}
	mi := &file_promo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promotion) ProtoMessage() {}

func (x *Promotion) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promotion.ProtoReflect.Descriptor instead.
func (*Promotion) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{2}
}

func (x *Promotion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Promotion) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

func (x *Promotion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Promotion) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreatePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogItemId string                 `protobuf:"bytes,1,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromoRequest) Reset() {
	*x = CreatePromoRequest{}
	mi := &file_promo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromoRequest) ProtoMessage() {}

func (x *CreatePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromoRequest.ProtoReflect.Descriptor instead.
func (*CreatePromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePromoRequest) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

func (x *CreatePromoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePromoRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreatePromoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromoResponse) Reset() {
	*x = CreatePromoResponse{}
	mi := &file_promo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromoResponse) ProtoMessage() {}

func (x *CreatePromoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromoResponse.ProtoReflect.Descriptor instead.
func (*CreatePromoResponse) Descriptor() ([]byte, []int) {
	return file_promo_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePromoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePromoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePromoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_promo_proto protoreflect.FileDescriptor

const file_promo_proto_rawDesc = "" +
	"\n" +
	"\vpromo.proto\x12\tpromotion\"F\n" +
	"\x1cGetPromoByCatalogItemRequest\x12&\n" +
	"\x0fcatalog_item_id\x18\x01 \x01(\tR\rcatalogItemId\"S\n" +
	"\x1dGetPromoByCatalogItemResponse\x122\n" +
	"\tpromotion\x18\x01 \x01(\v2\x14.promotion.PromotionR\tpromotion\"o\n" +
	"\tPromotion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fcatalog_item_id\x18\x02 \x01(\tR\rcatalogItemId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"h\n" +
	"\x12CreatePromoRequest\x12&\n" +
	"\x0fcatalog_item_id\x18\x01 \x01(\tR\rcatalogItemId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"a\n" +
	"\x13CreatePromoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription2\xcc\x01\n" +
	"\x10PromotionService\x12j\n" +
	"\x15GetPromoByCatalogItem\x12'.promotion.GetPromoByCatalogItemRequest\x1a(.promotion.GetPromoByCatalogItemResponse\x12L\n" +
	"\vCreatePromo\x12\x1d.promotion.CreatePromoRequest\x1a\x1e.promotion.CreatePromoResponseB:Z8github.com/n0en0o/marketplace/internal/promotion/grpc/pbb\x06proto3"

var (
	file_promo_proto_rawDescOnce sync.Once
	file_promo_proto_rawDescData []byte
)

func file_promo_proto_rawDescGZIP() []byte {
	file_promo_proto_rawDescOnce.Do(func() {
		file_promo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_promo_proto_rawDesc), len(file_promo_proto_rawDesc)))
	})
	return file_promo_proto_rawDescData
}

var file_promo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_promo_proto_goTypes = []any{
	(*GetPromoByCatalogItemRequest)(nil),  // 0: promotion.GetPromoByCatalogItemRequest
	(*GetPromoByCatalogItemResponse)(nil), // 1: promotion.GetPromoByCatalogItemResponse
	(*Promotion)(nil),                     // 2: promotion.Promotion
	(*CreatePromoRequest)(nil),            // 3: promotion.CreatePromoRequest
	(*CreatePromoResponse)(nil),           // 4: promotion.CreatePromoResponse
}
var file_promo_proto_depIdxs = []int32{
	2, // 0: promotion.GetPromoByCatalogItemResponse.promotion:type_name -> promotion.Promotion
	0, // 1: promotion.PromotionService.GetPromoByCatalogItem:input_type -> promotion.GetPromoByCatalogItemRequest
	3, // 2: promotion.PromotionService.CreatePromo:input_type -> promotion.CreatePromoRequest
	1, // 3: promotion.PromotionService.GetPromoByCatalogItem:output_type -> promotion.GetPromoByCatalogItemResponse
	4, // 4: promotion.PromotionService.CreatePromo:output_type -> promotion.CreatePromoResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_promo_proto_init() }
func file_promo_proto_init() {
	if File_promo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_promo_proto_rawDesc), len(file_promo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_promo_proto_goTypes,
		DependencyIndexes: file_promo_proto_depIdxs,
		MessageInfos:      file_promo_proto_msgTypes,
	}.Build()
	File_promo_proto = out.File
	file_promo_proto_goTypes = nil
	file_promo_proto_depIdxs = nil
}
