syntax = "proto3";

option go_package = "github.com/n0en0o/shop/internal/promotion/grpc/pb";

package greet;

// Greeter обеспечивает операцию приветствия
service Greeter {
    // SayHello отправляет ответ с приветствием для указанного имени
    rpc SayHello(HelloRequest) returns (HelloReply);
    rpc Add(AddRequest) returns (AddReply);
}

message HelloRequest {
    string name = 1;
}

message HelloReply {
    string msg = 1;
}

message AddRequest {
    int64 a = 1;
    int64 b = 2;
}

message AddReply {
    int64 result = 1;
}
