syntax = "proto3";

option go_package = "github.com/n0en0o/marketplace/internal/promotion/grpc/pb";

package promotion;

// PromotionService
service PromotionService {
    // GetPromoByCatalogItem
    rpc GetPromoByCatalogItem(GetPromoByCatalogItemRequest)
        returns (GetPromoByCatalogItemResponse);

    //CreatePromo
    rpc CreatePromo(CreatePromoRequest) 
        returns (CreatePromoResponse);

    //UpdatePromo
    rpc UpdatePromo(UpdatePromoRequest) 
        returns (UpdatePromoResponse);

    //DeletePromo
    rpc DeletePromo(DeletePromoRequest)
        returns (DeletePromoResponse);
}

message GetPromoByCatalogItemRequest {
    string catalog_item_id = 1;
}

message GetPromoByCatalogItemResponse {
    Promotion promotion = 1;
}

message Promotion {
    string id = 1;
    string catalog_item_id = 2;
    string title = 3;
    string value = 4;
}

message CreatePromoRequest {
    string catalog_item_id = 1;
    string title = 2;
    string value = 3;
}

message CreatePromoResponse {
    string id = 1;
    bool success = 2;
    string description = 3;
}

message UpdatePromoRequest {
    string id = 1;
    string title = 2;
    string value = 3;
}

message UpdatePromoResponse {
    bool success = 1;
    string description = 2;
}

message DeletePromoRequest {
    string id = 1;
}

message DeletePromoResponse {
    bool success = 1;
    string description = 2;
}
